services:
  mongodb:
    image: mongo:6
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - ${MONGODB_DATA_DIR}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - monsterbio-net
    restart: unless-stopped

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000" # inte public port längre
    env_file:
      - ./backend/.env
    environment:
      - PORT=${PORT}
    networks:
      - monsterbio-net
    restart: unless-stopped

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:80 # bara denna är publik nu
    depends_on:
      - backend
    networks:
      - monsterbio-net
    restart: unless-stopped

networks:
  monsterbio-net:
